### ISSUE TITLE
Validate Password

### ISSUE THREAD

**Issue by vickymhs** [NCSU-CSC540-Fall2021/Marketplace#2]
Write a function to validate the password while customer, brand and admin signup

**Comment by Jyoti28Dhikale** [comment]
Can you please assign me this issue?

**Comment by doboianh** [comment]
Can you please assign me this issue?

**Comment by truonghoangthuan** [comment]
![image](https://user-images.githubusercontent.com/58626520/140490360-64ddf97d-137a-4d96-b7cb-2a4684d07aa6.png)
Hello @vickymhs I created a regular expression to validate user password. I commented the password policies in my code, you can check it in this picture. I hope this can help the issue.

**Comment by truonghoangthuan** [comment]
I can help with this issue.

**Comment by vickymhs** [comment]
Thanks for all the responses! However it is an internal university grading project and I have these issues for the members working on it! Once I make it open, I will start accepting your solutions. Appreciate your time
